# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Department Mathematik der Universität Siegen'
description:      'Events'
url:              https://mathematik-siegen.github.io
baseurl:          ''

exclude: [ "LICENSE.hyde.md", "README.hyde.md" ]
